### GET all logs by user id
GET http://localhost:8080/users/1/logs

### GET log by date
GET http://localhost:8080/users/1/logs/2026-02-24


### POST log
POST http://localhost:8080/users/1/logs
Content-Type: application/json

{
}

#### DELETE log by id
DELETE http://localhost:8080/users/9/logs/27

#### POST poop to log by id
POST http://localhost:8080/users/1/logs/34
Content-Type: application/json

{
  "size": "GINORMOUS",
  "color": "DARK_BROWN",
  "softness": "SOFT"
}

#### POST foodseaten to log
POST http://localhost:8080/users/14/logs/36/foods
Content-Type: application/json

["broccoli"]
