### GET request to example server
GET http://localhost:8080/users/4/logs

###
GET http://localhost:8080/users/4/logs/2026-02-20


###
POST http://localhost:8080/users/6/logs
Content-Type: application/json

{
}
