### GET request to example server
GET http://localhost:8080/users/1/logs

###
GET http://localhost:8080/users/1/logs/2026-02-23


###
POST http://localhost:8080/users/14/logs
Content-Type: application/json

{
}

####
DELETE http://localhost:8080/users/9/logs/27

####
POST http://localhost:8080/users/1/logs/34
Content-Type: application/json

{
  "size": "GINORMOUS",
  "color": "DARK_BROWN",
  "softness": "SOFT"
}

####
POST http://localhost:8080/users/14/logs/36/foods
Content-Type: application/json

["broccoli"]
