### GET request to example server
GET http://localhost:8080/foods

###
POST http://localhost:8080/foods
Content-Type: application/json

{
  "name": "chicken thigh"
}


###
DELETE http://localhost:8080/foods/3