### GET all users
GET http://localhost:8080/users

### GET users by id
GET http://localhost:8080/users/14

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Fanni",
  "password": "fanni0430"
}

###
PUT  http://localhost:8080/users/1
Content-Type: application/json

{
  "name": "Kyo",
  "password": "kyosuke0527"
}
###
DELETE http://localhost:8080/users/13

###
GET  http://localhost:8080/users/1/safe-foods

###
POST http://localhost:8080/users/1/safe-foods
Content-Type: application/json

banana

###
DELETE  http://localhost:8080/users/1/safe-foods/17

