### GET all users
GET http://localhost:8080/users

### GET users by id
GET http://localhost:8080/users/2

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Ggggg",
  "password": "dddd1222"
}

###
PUT  http://localhost:8080/users/1
Content-Type: application/json

{
  "name": "Bbcc",
  "password": "bbcc2026"
}
###
DELETE http://localhost:8080/users/2