### GET all users
GET http://localhost:8080/users

### GET users by id
GET http://localhost:8080/users/4

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Aaaaa",
  "password": "aaaa2026"
}

###
PUT  http://localhost:8080/users/6
Content-Type: application/json

{
  "name": "Bbbbb",
  "password": "bbbb2026"
}
###
DELETE http://localhost:8080/users/2